name: Deploy Codice su Altervista 🚀

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: FTP Deploy (Solo Code)
    runs-on: ubuntu-latest
    
    steps:
    # 1. Scarica il codice dal repository
    - name: Get latest code
      uses: actions/checkout@v4
    
    # 2. Applica il Cache Busting sui file per Davide
    - name: Apply Cache Busting
      run: |
        VERSION_TAG="v=${{ github.sha }}"
        SHORT_TAG=$(echo ${VERSION_TAG} | cut -c1-9)
        sed -i "s/mobile.css/mobile.css?$SHORT_TAG/g" index.html
        sed -i "s/desktop.css/desktop.css?$SHORT_TAG/g" index.html
        sed -i "s/engine.js/engine.js?$SHORT_TAG/g" index.html
    
    # 3. Spara su Altervista (Ora che gli USA sono abilitati!)
    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        # Forza la connessione pulita monocanale
        port: 21
        protocol: ftp
        stateful: true
        
        # Ignora la cartella immagini sul server
        exclude: |
          **/immagini/**
          **/immagini
          **/.git*
          **/.git*/**
          README.md
